language: go

go:
  - 1.10.x

addons:
  apt:
    packages:
      - nodejs

go_import_path: github.com/norunners/vue

install:
  - npm install --global source-map-support
  - npm install --global node-gyp
  # Install the gopherjs tool.
  - go get -u github.com/gopherjs/gopherjs
  # Get the dependencies of vue.
  - go get github.com/norunners/vert
  # Get the dependencies of vueGen.
  - go get github.com/tdewolff/minify
  - go get github.com/dave/jennifer/jen

before_script:
  # Set up stack trace support for gopherjs with source-map-support.
  - export NODE_PATH="$(npm root --global)"
  # Set up system call support for gopherjs with node-gyp.
  # See documentation: https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md for details.
  - cd $GOPATH/src/github.com/gopherjs/gopherjs/node-syscall/
  - node-gyp rebuild
  - mkdir -p ~/.node_libraries/
  - cp build/Release/syscall.node ~/.node_libraries/syscall.node
  - cd $TRAVIS_BUILD_DIR

script:
  # Diff go format.
  - diff -u <(echo -n) <(gofmt -d .)
  # Run go vet.
  - go vet -v ./...
  # Run gopherjs unit tests.
  - gopherjs test -v
